allow-breeding: true
allow-ditto-ditto-breeding: true
allow-ranch-expansion: true
allow-random-breeding-eggs-to-be-legendary: false
allow-random-breeding-eggs-to-be-ultrabeast: false
breeding-ticks: 18000
max-cumulative-pokemon-in-ranch: 0
num-breeding-levels: 5
oval-charm-multiplier: 0.5
steps-per-egg-cycle: 255
use-breeding-environment: true
